# Generated by Django 3.2.8 on 2021-10-08 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_rename_musician_id_gig_musician'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
