# Generated by Django 3.2.8 on 2021-10-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gigs', '0002_rename_musician_id_gig_musician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('gig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gigs.gig')),
            ],
        ),
    ]
