# Generated by Django 3.2.8 on 2021-10-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='fan_id',
            new_name='fan',
        ),
        migrations.RenameField(
            model_name='rsvp',
            old_name='gig_id',
            new_name='gig',
        ),
    ]
