# Generated by Django 3.2.8 on 2021-10-07 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fans', '0002_alter_fan_user'),
        ('gigs', '0002_rename_musician_id_gig_musician'),
        ('rsvps', '0002_auto_20211007_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='fan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fans.fan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='gig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gigs.gig'),
            preserve_default=False,
        ),
    ]
